    build:
    - default.nix
    - CMakeLists.txt
    - build/*
    - build/**/*
    - cmake/*
    - cmake/**/*
    
    code quality:
    - src/test/*
    - src/test/**/*
    - .clang-format
    - .codespell
    - .eslint*
    - .flake8
    - .pre-commit-config.yaml
    - .travis.yml
    - appveyor.yml
    - pyproject.toml
      
    controllers:
    - res/controllers/*
      
    library:
    - src/library/*
    - src/library/**/*
      
    skins:
    - res/skins/*
    - res/skins/**/*
    
    ui:
    - src/dialog/*
    - src/preferences/*
    - src/widget/*
    - src/widget/**/*
