language: python
python:
- 3.7
os: linux
dist: xenial
cache:
  pip: true

if: type != pull_request AND branch =~ /^(manual-)/

install:
- sudo apt-get update && sudo apt-get install -y texlive texlive-xetex texlive-latex-extra latexmk xindy
- npm install -g netlify-cli
- export PATH="$(npm prefix -g)/bin:$PATH"
- pip install -r requirements.txt

script:
- mkdir html
- git remote rename origin fork
- git remote add origin https://github.com/mixxxdj/manual.git
- git fetch origin
- git branch -r
- export LATEST_BRANCH="$(git branch -r | grep -Po 'origin/manual-\d+\.\d+\.x' | sort | tail -n 1)"
- echo "Building from branch ${LATEST_BRANCH}"
- git checkout "${LATEST_BRANCH}"
- sh build_manual.sh

deploy:
  provider: script
  skip_cleanup: true
  script: netlify deploy --prod --dir build/html
