name: Build Manual

on:
  push:

jobs:
  build-html:
    name: HTML
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - name: Setup Graphviz
      run: sudo apt update && sudo apt install -y graphviz
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install Python dependencies
      run: pip install --upgrade -r requirements.txt
    - name: Build versioned HTML manual
      run: sh build_html.sh
    - name: Publish
      if: env.NETLIFY_SITE_ID != null && env.NETLIFY_AUTH_TOKEN != null
      uses: netlify/actions/cli@master
      timeout-minutes: 15
      with:
        args: deploy --prod --dir=build/html
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  build-pdf:
    name: PDF
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - name: Install build dependencies
      run: >
        sudo apt-get update && sudo apt-get install -y
        fonts-freefont-otf
        graphviz
        latexmk
        librsvg2-bin
        texlive
        texlive-generic-recommended
        texlive-lang-all
        texlive-latex-extra
        texlive-xetex
        xindy
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install Python dependencies
      run: pip install --upgrade -r requirements.txt
    - name: Build versioned PDF manual
      run: sh build_pdf.sh
    - name: Deploy PDFs to downloads.mixxx.org
      if: env.DOWNLOADS_HOSTGATOR_DOT_MIXXX_DOT_ORG_KEY_PASSWORD != null
      run: bash travis-deploy.sh
      env:
        DOWNLOADS_HOSTGATOR_DOT_MIXXX_DOT_ORG_KEY_PASSWORD: ${{ secrets.DOWNLOADS_HOSTGATOR_DOT_MIXXX_DOT_ORG_KEY_PASSWORD }}
